# Generated by Django 5.0.6 on 2026-05-29 11:22

import django.core.validators
import django.db.models.deletion
import proposals.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('land_type', models.CharField(choices=[('degraded_forest', 'Forêt dégradée'), ('savanna', 'Savane'), ('agricultural', 'Terrain agricole abandonné'), ('bare_land', 'Terrain nu'), ('riparian', "Zone riparienne (bord de cours d'eau)"), ('other', 'Autre')], max_length=30)),
                ('surface_hectares', models.DecimalField(decimal_places=2, help_text='Surface approximative déclarée par le Volontaire', max_digits=10, validators=[django.core.validators.MinValueValidator(0.5)])),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('address_full', models.TextField(blank=True)),
                ('address_country', models.CharField(blank=True, max_length=100)),
                ('address_region', models.CharField(blank=True, max_length=100)),
                ('address_city', models.CharField(blank=True, max_length=100)),
                ('nominatim_raw', models.JSONField(blank=True, default=dict, help_text='Réponse brute Nominatim')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente de validation'), ('pre_validated', 'Pré-validé (Admin)'), ('site_visit', 'Visite terrain en cours'), ('approved', 'Approuvé — en marketplace'), ('rejected', 'Rejeté'), ('suspended', 'Suspendu')], default='draft', max_length=20)),
                ('admin_review_note', models.TextField(blank=True)),
                ('admin_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('site_visit_date', models.DateField(blank=True, null=True)),
                ('site_visit_report', models.TextField(blank=True)),
                ('surface_confirmed_hectares', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('structure_validated_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('co2_estimated_tons', models.DecimalField(blank=True, decimal_places=2, help_text='Tonnes CO₂ séquestrées estimées sur 30 ans', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_reviewer', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_proposals', to=settings.AUTH_USER_MODEL)),
                ('structure_assigned', models.ForeignKey(blank=True, limit_choices_to={'role': 'structure'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_proposals', to=settings.AUTH_USER_MODEL)),
                ('volontaire', models.ForeignKey(limit_choices_to={'role': 'volontaire'}, on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'proposals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('title_deed', 'Titre foncier'), ('sale_act', 'Acte de vente'), ('customary_cert', 'Certificat coutumier'), ('donation_act', 'Acte de donation'), ('other', 'Autre document')], max_length=20)),
                ('file', models.FileField(upload_to=proposals.models.proposal_document_path)),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_note', models.TextField(blank=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='proposals.proposal')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'proposal_documents',
            },
        ),
        migrations.CreateModel(
            name='ProposalPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.ImageField(upload_to=proposals.models.proposal_photo_path)),
                ('exif_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('exif_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('exif_taken_at', models.DateTimeField(blank=True, null=True)),
                ('gps_distance_meters', models.IntegerField(blank=True, null=True)),
                ('exif_verified', models.BooleanField(default=False)),
                ('gps_match', models.BooleanField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='proposals.proposal')),
            ],
            options={
                'db_table': 'proposal_photos',
            },
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['status'], name='proposals_status_6b8498_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['volontaire'], name='proposals_volonta_0bf78f_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['address_country'], name='proposals_address_bdcf0a_idx'),
        ),
    ]
