# Generated by Django 5.0.6 on 2026-05-29 12:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_id', models.UUIDField(unique=True)),
                ('project_title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente de signatures'), ('signed', 'Signé par toutes les parties'), ('cancelled', 'Annulé')], default='draft', max_length=15)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='contracts/')),
                ('signed_by_volontaire', models.BooleanField(default=False)),
                ('signed_by_structure', models.BooleanField(default=False)),
                ('signed_by_admin', models.BooleanField(default=False)),
                ('volontaire_signed_at', models.DateTimeField(blank=True, null=True)),
                ('structure_signed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_signed_at', models.DateTimeField(blank=True, null=True)),
                ('document_hash', models.CharField(blank=True, help_text='SHA256 du PDF généré', max_length=64)),
                ('total_budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('duration_months', models.PositiveIntegerField(default=36)),
                ('platform_fee_percent', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('co2_estimated_tons', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('admin', models.ForeignKey(limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.PROTECT, related_name='contracts_as_admin', to=settings.AUTH_USER_MODEL)),
                ('mecenes', models.ManyToManyField(limit_choices_to={'role': 'mecene'}, related_name='contracts_as_mecene', to=settings.AUTH_USER_MODEL)),
                ('structure', models.ForeignKey(limit_choices_to={'role': 'structure'}, on_delete=django.db.models.deletion.PROTECT, related_name='contracts_as_structure', to=settings.AUTH_USER_MODEL)),
                ('volontaire', models.ForeignKey(limit_choices_to={'role': 'volontaire'}, on_delete=django.db.models.deletion.PROTECT, related_name='contracts_as_volontaire', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contracts',
            },
        ),
    ]
