# Generated by Django 5.0.6 on 2026-05-29 11:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_id', models.UUIDField(help_text='ID du projet associé', unique=True)),
                ('project_title', models.CharField(max_length=200)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('funded_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('released_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('locked_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('status', models.CharField(choices=[('awaiting_funds', 'En attente de fonds'), ('funded', 'Financé — travaux non démarrés'), ('in_progress', 'Travaux en cours'), ('completed', 'Projet terminé'), ('disputed', 'Litige en cours'), ('refunded', 'Remboursé')], default='awaiting_funds', max_length=20)),
                ('platform_fee_percent', models.DecimalField(decimal_places=2, default=20.0, help_text='% de commission Rebois Connect (défaut 20%)', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('funded_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'escrow_accounts',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('XAF', 'Franc CFA (CEMAC)'), ('XOF', 'Franc CFA (UEMOA)'), ('USD', 'Dollar américain')], default='EUR', max_length=3)),
                ('is_frozen', models.BooleanField(default=False, help_text='Wallet gelé par Admin (fraude suspectée)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='MeceneCommitment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(100)])),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'En attente de virement'), ('confirmed', 'Virement confirmé'), ('cancelled', 'Annulé'), ('refunded', 'Remboursé')], default='pending', max_length=15)),
                ('payment_proof', models.FileField(blank=True, help_text="Capture d'écran ou relevé bancaire du virement", null=True, upload_to='payment_proofs/')),
                ('payment_proof_verified', models.BooleanField(default=False)),
                ('co2_share_percent', models.DecimalField(decimal_places=2, default=0, help_text='% du financement total = % des crédits CO₂', max_digits=5)),
                ('co2_tons_allocated', models.DecimalField(decimal_places=2, default=0, help_text='Tonnes CO₂ allouées à ce Mécène', max_digits=10)),
                ('committed_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('escrow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commitments', to='wallet.escrowaccount')),
                ('mecene', models.ForeignKey(limit_choices_to={'role': 'mecene'}, on_delete=django.db.models.deletion.PROTECT, related_name='commitments', to=settings.AUTH_USER_MODEL)),
                ('payment_proof_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mecene_commitments',
                'unique_together': {('mecene', 'escrow')},
            },
        ),
    ]
