# Generated by Django 5.0.6 on 2026-05-31 16:53

import django.db.models.deletion
import kyc.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('id_card', "Carte d'identité"), ('passport', 'Passeport'), ('residence', 'Justificatif de domicile'), ('land_cert', 'Certificat foncier (Volontaire)'), ('org_cert', "Certificat d'organisation (Structure)"), ('tax_cert', 'Attestation fiscale'), ('other', 'Autre')], max_length=20)),
                ('file', models.FileField(upload_to=kyc.models.kyc_doc_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kyc_documents',
            },
        ),
        migrations.CreateModel(
            name='KYCReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approved', models.BooleanField()),
                ('note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviews_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_review', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kyc_reviews',
            },
        ),
    ]
