# Generated by Django 5.0.6 on 2026-05-29 12:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_id', models.UUIDField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(help_text='Ordre du milestone (1, 2, 3...)')),
                ('payment_percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('amount_to_release', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('submitted', 'Preuves soumises'), ('validated', 'Validé — paiement débloqué'), ('rejected', 'Rejeté — preuves insuffisantes')], default='pending', max_length=15)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_milestones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'milestones',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MilestoneProof',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proof_type', models.CharField(choices=[('photo', 'Photo terrain'), ('video', 'Vidéo'), ('report', 'Rapport technique'), ('invoice', 'Facture'), ('certificate', 'Certificat'), ('other', 'Autre')], max_length=15)),
                ('file', models.FileField(upload_to='milestone_proofs/')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('exif_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('exif_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_match', models.BooleanField(blank=True, null=True)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='milestones.milestone')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_proofs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'milestone_proofs',
            },
        ),
    ]
