# Generated by Django 5.0.6 on 2026-05-29 11:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('mecene_deposit', 'Dépôt Mécène → Escrow'), ('milestone_release', 'Déblocage milestone → Structure'), ('platform_fee', 'Commission plateforme'), ('refund', 'Remboursement Mécène'), ('withdrawal', 'Retrait vers compte bancaire')], max_length=25)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complétée'), ('failed', 'Échouée'), ('cancelled', 'Annulée')], default='pending', max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('description', models.TextField(blank=True)),
                ('reference', models.CharField(help_text='Référence unique de la transaction', max_length=100, unique=True)),
                ('milestone_id', models.UUIDField(blank=True, help_text='Milestone associé si déblocage', null=True)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authorized_transactions', to=settings.AUTH_USER_MODEL)),
                ('escrow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='wallet.escrowaccount')),
                ('from_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_transactions', to='wallet.wallet')),
                ('to_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_transactions', to='wallet.wallet')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['type', 'status'], name='transaction_type_f4191c_idx'), models.Index(fields=['escrow'], name='transaction_escrow__98b277_idx'), models.Index(fields=['from_wallet'], name='transaction_from_wa_14c6fe_idx'), models.Index(fields=['to_wallet'], name='transaction_to_wall_9c22a1_idx')],
            },
        ),
    ]
