# Generated by Django 5.0.6 on 2026-05-31 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_role_0ace22_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_kyc_sta_4052e1_idx',
        ),
    ]
