# Generated by Django 5.0.6 on 2026-05-29 12:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CO2Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=30, unique=True)),
                ('project_id', models.UUIDField()),
                ('project_title', models.CharField(max_length=200)),
                ('co2_tons_certified', models.DecimalField(decimal_places=2, max_digits=10)),
                ('co2_share_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('investment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('project_country', models.CharField(max_length=100)),
                ('project_region', models.CharField(blank=True, max_length=100)),
                ('surface_hectares', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('standard', models.CharField(choices=[('rebois_internal', 'Certificat Rebois Connect (MVP)'), ('label_bas_carbone', 'Label Bas Carbone (France/Europe)'), ('verra_vcs', 'Verra VCS (Mondial)'), ('gold_standard', 'Gold Standard (International)'), ('plan_vivo', 'Plan Vivo (Afrique/Asie)')], default='rebois_internal', max_length=25)),
                ('certification_body', models.CharField(blank=True, help_text='Organisme certificateur tiers', max_length=200)),
                ('registry_reference', models.CharField(blank=True, help_text='Référence dans le registre officiel', max_length=100)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('certificate_hash', models.CharField(blank=True, help_text="SHA256 — vérification d'authenticité", max_length=64)),
                ('status', models.CharField(choices=[('pending', 'En cours de génération'), ('issued', 'Émis'), ('revoked', 'Révoqué')], default='pending', max_length=10)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='contracts.contract')),
                ('mecene', models.ForeignKey(limit_choices_to={'role': 'mecene'}, on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'co2_certificates',
                'ordering': ['-issued_at'],
            },
        ),
    ]
